### ISSUE TITLE
Käyttäjän luonti Recser (Recserille pääsy käyttäjänhallintaan) & Admin tilin kautta

### ISSUE THREAD

**Issue by samuelmuittari** [softalaRyhma2/SR2#13]
Recser-käyttäjälle annetaan samat oikeudet kuin adminille, excel-taulukon mukaan

![Image](https://github.com/softalaRyhma2/SR2/assets/122819132/e8af124a-abfe-4c95-96af-17e1f6e65cf9)

**Comment by romeorusi** [comment]
User management näkyviin ja toimimaan recserinä kirjautuneelle
