### ISSUE TITLE
Käsittelylaitoksena/kuljetusliikkeenä stock hinnan muokkaaminen kielletty

### ISSUE THREAD

**Issue by romeorusi** [softalaRyhma2/SR2#41]

**Comment by romeorusi** [comment]
Hinta valmiina jos luo uuden stockin

**Comment by piialairi** [comment]
Tällä hetkellä vain admin tai recser voi muokata stock itemin hintaa ja hinta-kenttä on piilotettu muilta kuin adminilta tai recseriltä. 
Tätä toteutusta pitää todennäköisesti muuttaa projektin edetessä niin, että hinta määräytyy jonkin edellisen mukaan tjsp
