### ISSUE TITLE
jdl muutos lavan tuotetyypin seuraamiseen ja README.md päivitys

### ISSUE THREAD

**Issue by romeorusi** [softalaRyhma2/SR2#44]

**Comment by dovile-mart** [comment]
**Readme.md:n päivitykset** ([Linkki committiin](https://github.com/softalaRyhma2/SR2/commit/61b643c6852a0c23e01b3f943503faff0c02c692))
1. Käyttöliittymän osion linkit videoihin.
2. Tietohakemisto: 
-- Company
-- Invoice
-- Stock
-- StockItem
-- StockItemType
-- Reservation
-- ReservedItem
