### ISSUE TITLE
invoices->company->back vie väärään kohtaan

### ISSUE THREAD

**Issue by romeorusi** [softalaRyhma2/SR2#49]

**Comment by dovile-mart** [comment]
company-detail.tsx:ssa loin handleGoBack-funktion ja kommentoin pois vanha reititys (poistan myöhemmin, jos ei tule mitään ongelmia). Tähän asti ainakin mulla on toiminut kaikkilla käyttäjillä eikä mitään erroreja oo.

![Image](https://github.com/softalaRyhma2/SR2/assets/71691245/a3d7186e-b807-4527-84c1-b7dd79098736)
