### ISSUE TITLE
invoices edit company kenttä kirjautumisen perusteella (ei vaihdettava)

### ISSUE THREAD

**Issue by romeorusi** [softalaRyhma2/SR2#50]

**Comment by dovile-mart** [comment]
**muokkaus**-vaiheessa näkyy pelkästään organisaation nimi:



![Image](https://github.com/softalaRyhma2/SR2/assets/71691245/b6ef4292-3f7c-4e5d-b94c-07ee1f78beca)





**luonti**-vaiheessa näkyy kaikki:

![Image](https://github.com/softalaRyhma2/SR2/assets/71691245/25de3ddc-8b17-4f76-b489-74913ad26c90)
