### ISSUE TITLE
Create or edit stock invoice id:tä ei voi saada muuttaa

### ISSUE THREAD

**Issue by romeorusi** [softalaRyhma2/SR2#51]

**Comment by dovile-mart** [comment]
**luonti**:

![Image](https://github.com/softalaRyhma2/SR2/assets/71691245/e1a06c44-ed8b-40cf-8333-b0664c0ce25e)

**muokkaus**:

![Image](https://github.com/softalaRyhma2/SR2/assets/71691245/beadf3fe-5302-4b44-b6a8-3a406c190305)
